id: P5D632458
initial_creation_type: input
source_metadata:
  title: Vairotsana Series
  language: bo
  description: 'Texts by and about Pagor Vairotsana (fl. 8th C.), the greatest of
    the early Tibetan translators:'
  volume:
    c3b22caed5cc40ae8538ec21b27f94ea:
      title: Sādhana of the Great Master Vairotsana
      parent: Sādhanas
created_at: '2022-03-01T02:00:38.194577'
last_modified_at: '2022-03-01T02:00:38.194580'
statistics:
  total_words: 455
  total_non_words: 35
quality:
  non_words_ratio: 0.08
